### ISSUE TITLE
Please fix repo address 

### ISSUE THREAD

**Issue by pcav** [havatv/qgisstandarddeviationalellipseplugin#1]
The one in metadata hives 404.
Thanks.

**Comment by havatv** [comment]
OK.
I changed it by editing on http://plugins.qgis.org, and
thought that was enough.  I will update metadata.txt too
and upload again later today.

Håvard

**Comment by havatv** [comment]
Should be fixed in the version I uploaded just now.

**Comment by pcav** [comment]
Seems still wrong: https://github.com/havatv/qgisstandarddeviationalellipsepluginq
Please check http://plugins.qgis.org/plugins/SDEllipse/

**Comment by havatv** [comment]
Thanks.  There were two problematic links. I only fixed the link to the homepage.  Should be OK now.

**Comment by pcav** [comment]
sorry, there is still a final 'q' that breaks the link

**Comment by havatv** [comment]
It was fixed in metadata.txt, now I have also fixed it on http://plugins.qgis.org/plugins/SDEllipse/
